-- MySQL Script generated by MySQL Workbench
-- Fri Jul 12 14:34:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema demo_examsystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema demo_examsystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demo_examsystem` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `demo_examsystem` ;

-- -----------------------------------------------------
-- Table `demo_examsystem`.`batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_examsystem`.`batch` (
  `batch_id` INT NOT NULL AUTO_INCREMENT COMMENT '批次',
  `batch_name` VARCHAR(50) NOT NULL COMMENT '批次名称',
  `year` CHAR(4) NOT NULL COMMENT '关联年份',
  `start_date` DATE NOT NULL COMMENT '报名开始时间',
  `end_date` DATE NOT NULL COMMENT '报名结束时间',
  `description` VARCHAR(255) NULL DEFAULT NULL COMMENT '描述',
  `attachment` VARCHAR(255) NULL DEFAULT NULL COMMENT '附件',
  PRIMARY KEY (`batch_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '批次表';


-- -----------------------------------------------------
-- Table `demo_examsystem`.`examination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_examsystem`.`examination` (
  `exam_id` INT NOT NULL AUTO_INCREMENT COMMENT '考试编号',
  `batch_id` INT NOT NULL COMMENT '批次',
  `exam_room` VARCHAR(50) NOT NULL COMMENT '考场',
  `campus` VARCHAR(50) NOT NULL COMMENT '校区',
  `address` VARCHAR(255) NULL DEFAULT NULL COMMENT '考试地点',
  `from_time` DATETIME NOT NULL COMMENT '考试开始时间',
  `end_time` DATETIME NOT NULL COMMENT '考试结束时间',
  PRIMARY KEY (`exam_id`),
  INDEX `Examination_from_Batch` (`batch_id` ASC) VISIBLE,
  CONSTRAINT `Examination_from_Batch`
    FOREIGN KEY (`batch_id`)
    REFERENCES `demo_examsystem`.`batch` (`batch_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '考试表';


-- -----------------------------------------------------
-- Table `demo_examsystem`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_examsystem`.`user` (
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `usertype` INT NULL DEFAULT NULL,
  `is_deleted` TINYINT(1) NULL DEFAULT NULL,
  `is_enable` TINYINT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo_examsystem`.`personnel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_examsystem`.`personnel` (
  `name` VARCHAR(50) NOT NULL COMMENT '姓名',
  `unit` VARCHAR(50) NOT NULL COMMENT '单位',
  `gender` CHAR(2) NOT NULL COMMENT '性别',
  `edu_background` VARCHAR(50) NOT NULL COMMENT '学历',
  `phone` CHAR(11) NOT NULL COMMENT '电话',
  `backup_phone` CHAR(11) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL COMMENT '电话(备用)',
  `photo` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL COMMENT '照片',
  `username` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `fk_personnel_user1_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_personnel_user1`
    FOREIGN KEY (`username`)
    REFERENCES `demo_examsystem`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '人员表';


-- -----------------------------------------------------
-- Table `demo_examsystem`.`signup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_examsystem`.`signup` (
  `exam_id` INT NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `approval_status` INT NOT NULL,
  `intended_campus` VARCHAR(45) NOT NULL,
  `reson` VARCHAR(45) NULL,
  `way` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`exam_id`, `username`),
  INDEX `fk_examination_has_personnel_personnel1_idx` (`username` ASC) VISIBLE,
  INDEX `fk_examination_has_personnel_examination1_idx` (`exam_id` ASC) VISIBLE,
  CONSTRAINT `fk_examination_has_personnel_examination1`
    FOREIGN KEY (`exam_id`)
    REFERENCES `demo_examsystem`.`examination` (`exam_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_examination_has_personnel_personnel1`
    FOREIGN KEY (`username`)
    REFERENCES `demo_examsystem`.`personnel` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
